-- Analytics and User Preference Tracking
-- Run this in Supabase SQL Editor

-- Table to store user interactions for analytics and recommendations
CREATE TABLE IF NOT EXISTS user_interactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL,
  news_id UUID NOT NULL,
  interaction_type TEXT NOT NULL,
  metadata JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Index for fast user history lookup
CREATE INDEX IF NOT EXISTS idx_user_interactions_user_id ON user_interactions(user_id);
CREATE INDEX IF NOT EXISTS idx_user_interactions_created_at ON user_interactions(created_at DESC);

-- Table to store explicit user preferences (Weighted categories)
CREATE TABLE IF NOT EXISTS user_preferences (
  user_id UUID NOT NULL,
  category TEXT NOT NULL,
  weight INTEGER DEFAULT 0,
  updated_at TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (user_id, category)
);
2
-- Table to store real-time category scores (manually incremented for performance)
CREATE TABLE IF NOT EXISTS user_category_scores_manual (
  user_id UUID NOT NULL,
  category TEXT NOT NULL,
  score INTEGER DEFAULT 0,
  updated_at TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (user_id, category)
);

-- Index for fast lookups
CREATE INDEX IF NOT EXISTS idx_user_category_scores_user_id ON user_category_scores_manual(user_id);

-- View to calculate User Category Scores efficiently
-- This aggregates interactions into scores per category
CREATE OR REPLACE VIEW user_category_scores AS
SELECT
  ui.user_id,
  ni.category,
  SUM(
    CASE
      WHEN ui.interaction_type = 'like' THEN 5
      WHEN ui.interaction_type = 'expand' THEN 3
      WHEN ui.interaction_type = 'share' THEN 4
      WHEN ui.interaction_type = 'question_click' THEN 2
      WHEN ui.interaction_type = 'time_spent'
        THEN LEAST(
          COALESCE(((ui.metadata->>'timeSpent')::int / 5), 0),
          10
        )
      ELSE 0
    END
  ) AS score
FROM user_interactions ui
JOIN aggregated_stories ni ON ui.news_id = ni.id
WHERE ui.created_at > (now() - INTERVAL '30 days')
GROUP BY ui.user_id, ni.category;
