-- ==========================================
-- CONSOLIDATED SUPABASE INITIALIZATION SCRIPT
-- ==========================================

-- 1. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. TABLES

-- Event clusters table to group similar articles
CREATE TABLE IF NOT EXISTS event_clusters (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    representative_title TEXT,
    entity_fingerprint TEXT[],
    article_count INTEGER DEFAULT 0,
    representative_embedding JSONB -- Cached AI embedding for the representative title
);

-- Main news items table (raw ingestion)
CREATE TABLE IF NOT EXISTS news_items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title TEXT NOT NULL,
    summary JSONB, -- Storing array as JSONB
    "leftPerspective" TEXT,
    "rightPerspective" TEXT,
    "imageURL" TEXT,
    "youtubeID" TEXT,
    "clipUrl" TEXT,
    "clipDuration" FLOAT,
    "titleAudioPath" TEXT,
    "descriptionAudioPath" TEXT,
    "claimAudioPath" TEXT,
    "articleURL" TEXT,
    "sourceAPI" TEXT,
    claims JSONB,
    date TIMESTAMP WITH TIME ZONE,
    category TEXT DEFAULT 'Current',
    status TEXT DEFAULT 'INGESTED',
    "isOptimized" BOOLEAN DEFAULT FALSE,
    "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    cluster_id UUID REFERENCES event_clusters(id)
);

-- Aggregated stories table for the unified posts
CREATE TABLE IF NOT EXISTS aggregated_stories (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    cluster_id UUID REFERENCES event_clusters(id) UNIQUE,
    title TEXT NOT NULL,
    summary JSONB, -- Unified bullet points
    "leftPerspective" TEXT,
    "rightPerspective" TEXT,
    claim TEXT,
    "sourceCount" INTEGER,
    sources JSONB, -- Array of { sourceAPI, iconURL, articleURL, originalTitle }
    "titleAudioPath" TEXT,
    "descriptionAudioPath" TEXT,
    "claimAudioPath" TEXT,
    "youtubeID" TEXT,
    "clipUrl" TEXT,
    "clipDuration" FLOAT,
    date TIMESTAMP WITH TIME ZONE,
    category TEXT DEFAULT 'Current',
    status TEXT DEFAULT 'PENDING',
    "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Table for storing RSS feed sources
CREATE TABLE IF NOT EXISTS rss_feeds (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    url TEXT NOT NULL UNIQUE,
    category TEXT DEFAULT 'General',
    enabled BOOLEAN DEFAULT TRUE,
    "lastFetched" TIMESTAMP WITH TIME ZONE,
    "failureCount" INTEGER DEFAULT 0,
    "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- User interaction tracking
CREATE TABLE IF NOT EXISTS user_interactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL, -- references auth.users(id)
    news_id UUID NOT NULL, -- references aggregated_stories(id)
    interaction_type TEXT NOT NULL, -- 'like', 'view', 'expand', 'share', 'question_click', 'swipe_left', 'swipe_right', 'time_spent'
    metadata JSONB DEFAULT '{}'::jsonb, -- Store extra data like { timeSpent: 15 }
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- User category preferences
CREATE TABLE IF NOT EXISTS user_preferences (
    user_id UUID NOT NULL,
    category TEXT NOT NULL,
    weight INTEGER DEFAULT 0, -- 0=Hidden/Block, 1=Dampen, 2=Neutral, 3=Boost
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    PRIMARY KEY (user_id, category)
);

-- User voting system
CREATE TABLE IF NOT EXISTS user_votes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id TEXT NOT NULL,
    story_id UUID NOT NULL REFERENCES aggregated_stories(id) ON DELETE CASCADE,
    vote TEXT CHECK (vote IN ('agree', 'disagree')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(user_id, story_id)
);

-- 3. INDEXES
CREATE INDEX IF NOT EXISTS idx_status ON news_items(status);
CREATE INDEX IF NOT EXISTS idx_date ON news_items(date DESC);
CREATE INDEX IF NOT EXISTS idx_cluster_id ON news_items(cluster_id);
CREATE INDEX IF NOT EXISTS idx_aggregated_status ON aggregated_stories(status);
CREATE INDEX IF NOT EXISTS idx_aggregated_date ON aggregated_stories(date DESC);
CREATE INDEX IF NOT EXISTS idx_user_interactions_user_id ON user_interactions(user_id);
CREATE INDEX IF NOT EXISTS idx_user_interactions_created_at ON user_interactions(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_votes_story_id ON user_votes(story_id);

-- 4. VIEWS

-- User Category Scores for recommendations
CREATE OR REPLACE VIEW user_category_scores AS
SELECT 
    ui.user_id,
    as_stories.category,
    SUM(
        CASE 
            WHEN ui.interaction_type = 'like' THEN 5
            WHEN ui.interaction_type = 'expand' THEN 3
            WHEN ui.interaction_type = 'share' THEN 4
            WHEN ui.interaction_type = 'question_click' THEN 2
            WHEN ui.interaction_type = 'time_spent' THEN LEAST(FLOOR(COALESCE((ui.metadata->>'timeSpent')::int, 0) / 5), 10)
            ELSE 0 
        END
    ) as score
FROM 
    user_interactions ui
JOIN 
    aggregated_stories as_stories ON ui.news_id = as_stories.id
WHERE 
    ui.created_at > (NOW() - INTERVAL '30 days')
GROUP BY 
    ui.user_id, as_stories.category;

-- Story Vote Statistics
CREATE OR REPLACE VIEW story_vote_stats AS
SELECT 
    story_id,
    COUNT(*) FILTER (WHERE vote = 'agree') as agree_count,
    COUNT(*) FILTER (WHERE vote = 'disagree') as disagree_count
FROM user_votes
GROUP BY story_id;

-- 5. SEED DATA (RSS FEEDS)
INSERT INTO rss_feeds (name, url, category) VALUES
    ('NYT Home', 'https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml', 'General'),
    ('BBC Top Stories', 'http://feeds.bbci.co.uk/news/rss.xml', 'General'),
    ('CNN Top Stories', 'http://rss.cnn.com/rss/cnn_topstories.rss', 'General'),
    ('The Verge', 'https://www.theverge.com/rss/index.xml', 'Tech'),
    ('TechCrunch', 'https://techcrunch.com/feed/', 'Tech'),
    ('Wired', 'https://www.wired.com/feed/rss', 'Tech'),
    ('Hacker News', 'https://news.ycombinator.com/rss', 'Tech'),
    ('WSJ Markets', 'https://feeds.a.dj.com/rss/RSSMarketsMain.xml', 'Finance'),
    ('CNBC Finance', 'https://www.cnbc.com/id/10000664/device/rss/rss.html', 'Finance'),
    ('CoinDesk', 'https://www.coindesk.com/arc/outboundfeeds/rss/', 'Crypto'),
    ('Fox News', 'https://moxie.foxnews.com/google-publisher/latest.xml', 'General'),
    ('Fox News Politics', 'https://moxie.foxnews.com/google-publisher/politics.xml', 'Politics'),
    ('Fox Business', 'https://moxie.foxnews.com/google-publisher/business.xml', 'Finance'),
    ('MSNBC Top Stories', 'https://feeds.nbcnews.com/msnbc/public/all', 'General'),
    ('Reuters World', 'https://www.reutersagency.com/feed/?best-topics=political-general&post_type=best', 'General')
ON CONFLICT (url) DO NOTHING;

-- 6. STORAGE SETUP

-- Ensure 'clips' bucket exists and is public
INSERT INTO storage.buckets (id, name, public)
VALUES ('clips', 'clips', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Storage Policies
CREATE POLICY "Public Uploads" ON storage.objects FOR INSERT WITH CHECK ( bucket_id = 'clips' );
CREATE POLICY "Public Downloads" ON storage.objects FOR SELECT USING ( bucket_id = 'clips' );
CREATE POLICY "Public Updates" ON storage.objects FOR UPDATE USING ( bucket_id = 'clips' );
CREATE POLICY "Public Deletes" ON storage.objects FOR DELETE USING ( bucket_id = 'clips' );
